copyright = "© RC"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "America/Chicago"
timeout = "120s"
title = "Gallery"
theme = "gallery"

[params]
  defaultTheme = "dark"
  description = "alinuxuser gallery"
  title = "Gallery"
  [params.author]
    email = "alinuxuser@fastmail.com"
    name = "RC"
  [params.socialIcons]
    #facebook = "https://www.facebook.com/"
    #instagram = "https://www.instagram.com/"
    #github = "https://github.com/nicokaiser/hugo-theme-gallery/"
    #youtube = "https://www.youtube.com/"
    email = "mailto:alinuxuser@fastmail.com"
    #website = "https://example.com"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"
    #mixcloud = "https://example.com"
    #flickr = "https://www.flickr.com"
    #500px = "https://500px"
    #whatsapp = "1234567890"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"

[menu]
  [[menu.footer]]
    #name = "Blog"
    #url = "https://alinuxuser.com/"
    #weight = 2

[services]
  [services.rss]
    limit = 100
